import type { BlockerConfig, BlockerCategory } from '@/stores/pomodoroStore';

// Curated, high-impact domain lists per category — mirrors the browser
// extension's list so the desktop hosts-blocker blocks the same sites.
export const CATEGORY_DOMAINS: Record<BlockerCategory, string[]> = {
  // Curated, high-impact domain lists per category (worldwide). Researched from
  // reputable public references; these rotate, so refresh periodically. For
  // malware/phishing a maintained live feed is the real answer (static is stale).
  distracting: [
    'instagram.com', 'tiktok.com', 'twitter.com', 'x.com', 'facebook.com',
    'reddit.com', 'youtube.com', 'twitch.tv', 'netflix.com', 'pinterest.com',
    '9gag.com', 'tumblr.com', 'snapchat.com', 'whatsapp.com', 'telegram.org',
    'discord.com', 'linkedin.com', 'quora.com', 'buzzfeed.com', 'imgur.com',
    'primevideo.com', 'hulu.com', 'disneyplus.com',
  ],
  // Ad / pop-under / redirect / tracker networks — the infrastructure behind
  // betting, adult and "junk" ads (especially the pop-unders on streaming &
  // download sites). Blocking the registrable domain blocks all its subdomains,
  // so the ads never load; the browser extension additionally auto-closes any
  // pop-up tab that still slips through. Curated from reputable public adblock
  // lists (EasyList/EasyPrivacy, AdGuard, Hagezi, Peter Lowe, StevenBlack).
  ads: [
    '2mdn.net', '33across.com', '3lift.com', 'aax.media', 'acuityads.com',
    'ad-maven.com', 'adamoads.com', 'adblade.com', 'adcash.com', 'adcolony.com',
    'adelphic.com', 'adexchangeprediction.com', 'adextrem.com', 'adforcast.com', 'adform.net',
    'adform.ru', 'adgear.com', 'adgrx.com', 'adition.com', 'adk2.com',
    'admaven.com', 'adnium.com', 'adnow.com', 'adnxs-simple.com', 'adnxs.com',
    'adnxs.net', 'adroll.com', 'adsafeprotected.com', 'adscore.com', 'adsexo.com',
    'adsformarket.com', 'adskeeper.co.uk', 'adskeeper.com', 'adsmatemedia.com', 'adspyglass.com',
    'adsrvr.com', 'adsrvr.org', 'adsterra.com', 'adsterraserver.com', 'adsterratech.com',
    'adsupply.com', 'adsupplyads.com', 'adsupplyads.net', 'adsupplyssl.com', 'adswizz.com',
    'adsymptotic.com', 'adtelligent.com', 'adtheorent.com', 'adtng.com', 'advertising.com',
    'adxserve.com', 'adxxx.com', 'agkn.com', 'amazon-adsystem.com', 'amobee.com',
    'aniview.com', 'applovin.com', 'appnexus.com', 'aqfer.com', 'bidr.io',
    'bidswitch.net', 'bidvertiser.com', 'bluekai.com', 'bullionyield.com', 'casalemedia.com',
    'chartbeat.com', 'chartbeat.net', 'chartboost.com', 'clickadilla.com', 'clickadilla.net',
    'clickadu.com', 'clickadu.net', 'clickaine.com', 'clickdaly.com', 'clickpapa.com',
    'clksite.com', 'content.ad', 'contentabc.com', 'contextweb.com', 'cpx24.com',
    'crakrevenue.com', 'criteo.com', 'criteo.net', 'crwdcntrl.net', 'demdex.net',
    'dianomi.com', 'districtm.ca', 'districtm.io', 'doubleclick.com', 'doubleclick.net',
    'doublepimp.com', 'doubleverify.com', 'dpinteractive.com', 'eabids.com', 'effectivecreativeformats.com',
    'engageya.com', 'ero-advertising.com', 'eroadvertising.com', 'etology.com', 'evadav.com',
    'evadavdsp.pro', 'everesttech.net', 'exads.com', 'exdynsrv.com', 'exelator.com',
    'exoclick.com', 'exosrv.com', 'exoticads.com', 'exv6.com', 'eyeota.net',
    'fullstory.com', 'galaksion.com', 'gammassp.com', 'google-analytics.com', 'googleadservices.com',
    'googlesyndication.com', 'googletagservices.com', 'gumgum.com', 'highperformanceformat.com', 'hilltopads.com',
    'hilltopads.net', 'hotjar.com', 'illumin.com', 'improvedigital.com', 'indexww.com',
    'infolinks.com', 'inmobi.com', 'ipredictive.com', 'jediads.com', 'juicyads.com',
    'juicyads.in', 'juicyads.me', 'kadam.net', 'krxd.net', 'lijit.com',
    'magsrv.com', 'mathtag.com', 'media.net', 'mediaxx.net', 'mgid.com',
    'moatads.com', 'mobfox.com', 'monetag.com', 'monetixads.com', 'mopub.com',
    'mouseflow.com', 'mybetterdeals.com', 'mybid.io', 'nativo.com', 'onclckds.com',
    'onclicka.com', 'onclickaclk.com', 'onclickads.net', 'onclickalgo.com', 'openx.net',
    'optnx.com', 'orbsrv.com', 'outbrain.com', 'peerclick.com', 'plista.com',
    'plugrush.com', 'pnperf.com', 'polluxnetwork.com', 'popads.media', 'popads.net',
    'popca.sh', 'popcash.net', 'popmyads.com', 'poprtb.pro', 'poptm.com',
    'popunder.bid', 'popunder.com', 'popunder.net', 'popunder.ru', 'propellerads.com',
    'propellerads.tech', 'propellerpops.com', 'propu.sh', 'pubmatic.com', 'pubmine.com',
    'push.house', 'quantcount.com', 'quantserve.com', 'realsrv.com', 'realsrvcdn.com',
    'revcontent.com', 'revjet.com', 'revopush.com', 'richads.com', 'rivertraffic.com',
    'rlcdn.com', 'royalads.net', 'rubiconproject.com', 'scorecardresearch.com', 'serving-sys.com',
    'sharethrough.com', 'slimspots.com', 'smaato.com', 'smac-ad.com', 'smartadserver.com',
    'smartadserver.de', 'smartclip.net', 'smartstream.tv', 'sonobi.com', 'sovrn.com',
    'spotx.tv', 'spotxchange.com', 'star-advertising.com', 'startapp.com', 'stickyadstv.com',
    'taboola.com', 'tapad.com', 'teads.com', 'teads.tv', 'trafficfactory.biz',
    'trafficfactory.com', 'trafficforce.com', 'traffichaus.com', 'traffichouse.com', 'traffichunt.com',
    'trafficjunky.com', 'trafficjunky.net', 'trafficreps.com', 'trafficshop.com', 'trafficstars.com',
    'triplelift.com', 'tsyndicate.com', 'tsyndicate.net', 'tubecorporate.com', 'twinred.com',
    'tynt.com', 'viantinc.com', 'viglink.com', 'vungle.com', 'yieldlab.net',
    'yieldmo.com', 'youradexchange.com', 'zedo.com', 'zergnet.com', 'zeropark.com',
  ],
  gambling: [
    'bet365.com', 'betano.com', 'betano.pt', 'betway.com', '1xbet.com',
    'bwin.com', 'pokerstars.com', 'stake.com', 'draftkings.com', 'fanduel.com',
    'williamhill.com', 'betfair.com', '888casino.com', '888sport.com', 'ladbrokes.com',
    'unibet.com', 'betclic.com', 'sportingbet.com', 'betsson.com', 'parimatch.com',
    'melbet.com', '22bet.com', 'pinnacle.com', 'blaze.com', 'casino.com',
    'leovegas.com', 'rivalo.com', 'kto.com', 'estrelabet.com', 'betano.com.br',
    'betano.bet.br', 'betfair.com.br', '888.com', '888poker.com', 'pokerstars.pt',
    'pokerstars.com.br', 'stake.bet.br', 'bovada.lv', 'betonline.ag', 'bwin.pt',
    'paddypower.com', 'betsafe.com', 'nordicbet.com', 'tipico.com', 'betclic.pt',
    'megapari.com', 'gamdom.com', 'roobet.com', 'duelbits.com', 'rollbit.com',
    'bc.game', 'sportsbet.io', 'cloudbet.com', 'mystake.com', 'mrgreen.com',
    'casumo.com', 'rizk.com', 'sbobet.com', 'dafabet.com', 'caesars.com',
    'betmgm.com', 'borgataonline.com', 'hardrock.bet', 'espnbet.com', 'pointsbet.com',
    'sisal.it', 'snai.it', 'eurobet.it', 'goldbet.it', 'lottomatica.it',
    'sportingbet.bet.br', 'codere.es', 'luckia.pt', 'solverde.pt', 'placard.pt',
    'esc-online.pt', 'casinoportugal.pt', 'nossaaposta.pt', 'bacanaplay.pt', 'goldenpark.pt',
    'lebull.pt', 'bidluck.pt', 'moosh.pt', 'betnacional.com', 'betnacional.bet.br',
    'estrelabet.bet.br', 'blaze.bet.br', 'kto.bet.br', 'superbet.com', 'superbet.bet.br',
    'superbet.ro', 'bet7k.com', 'bet7k.bet.br', 'reidopitaco.bet.br', 'brazino777.com',
    'pixbet.com', 'pixbet.bet.br', 'vaidebet.bet.br', 'sportybet.com', 'bet9ja.com',
    'caliente.mx', 'stoiximan.gr', 'chumbacasino.com', 'vbet.com', 'wazamba.com',
    'betrivers.com', 'sportsbook.fanatics.com', 'hardrockbet.com', 'goldennuggetcasino.com', 'goldennuggetsports.com',
    'wynnbet.com', 'foxbet.com', 'sisportsbook.com', 'betparx.com', 'thescore.bet',
    'ballybet.com', 'prizepicks.com', 'underdogfantasy.com', 'underdogsports.com', 'sleeper.com',
    'novig.us', 'fliff.com', 'betr.app', 'betrpicks.com', 'stake.us',
    'pulsz.com', 'mcluck.com', 'highnooncasino.com', 'luckylandslots.com', 'funzpoints.com',
    'wowvegas.com', 'high5casino.com', 'fortunecoins.com', 'mybookie.ag', 'xbet.ag',
    'betnow.eu', 'sportsbetting.ag', 'betus.com', 'betus.com.pa', 'everygame.eu',
    'bookmaker.eu', 'betanysports.eu', 'betanything.eu', 'gtbets.com', 'betwinner.com',
    '20bet.com', 'cbet.gg', 'bitstarz.com', 'mbitcasino.com', 'fairspin.io',
    '7bitcasino.com', 'betfury.com', 'thunderpick.io', '500.casino', 'csgoempire.com',
    '888starz.bet', 'linebet.com', '4rabet.com', '10bet.com', 'gg.bet',
    'hollywoodbets.net', 'betway.co.za', 'supabets.co.za', 'sunbet.co.za', 'worldsportsbetting.co.za',
    'gbets.co.za', 'easybet.co.za', 'sportingbet.co.za', 'betxchange.com', 'yesplay.bet',
    'playabets.co.za', '10bet.co.za', 'lottostar.co.za', 'worldofsport.co.za', 'goldrush.co.za',
    'topbet.co.za', 'bet.co.za', 'premierbet.co.mz', 'betpawa.co.mz', '22bet.co.mz',
    'hollywoodbets.co.mz', 'elephantbet.co.mz', 'betway.co.mz', '888bets.co.mz', 'jogabets.co.mz',
    'placard.co.mz', 'olabet.co.mz', '1xbet.co.mz', 'premierbet.co.ao', 'elephantbet.co.ao',
    'bantubet.co.ao', '888bets.co.ao', 'betway.co.ao', 'parimatch.in', '10cric.com',
    'rajabets.com', 'fairplay.club', 'lotus365.com', 'mostbet.com', '1win.com',
    'batery.com', 'indibet.com', 'rummycircle.com', 'jungleerummy.com', 'a23.com',
    'pokerbaazi.com', 'adda52.com', 'betking.com', 'nairabet.com', 'merrybet.com',
    'betpawa.com', 'betpawa.co.ke', 'betpawa.ng', 'sportpesa.com', 'betika.com',
    'odibets.com', 'mozzartbet.com', 'mozzartbet.co.ke', 'galsport.com', 'premierbet.com',
    'msport.com', 'betlion.com', '12bet.com', 'w88.com', 'fun88.com',
    'm88.com', 'bk8.com', 'me88.com', '96ace.com', 'hfive5.com',
    'maxbet.com', 'cmd368.com', 'sportsbet.com.au', 'tab.com.au', 'ladbrokes.com.au',
    'neds.com.au', 'pointsbet.com.au', 'bet365.com.au', 'betr.com.au', 'unibet.com.au',
    'palmerbet.com', 'topsport.com.au', 'dabble.com', 'fonbet.com', '1xstavka.ru',
    'betboom.ru', 'marathonbet.com', 'olimpbet.com', 'pin-up.com', 'leon.ru',
    'misli.com', 'nesine.com', 'bilyoner.com', 'tuttur.com', 'oley.com',
    'birebin.com', 'rushbet.co', 'wplay.co', 'playdoit.com', 'strendus.com.mx',
    'betplay.com.co', 'luckia.com', 'sportium.es', 'zamba.co', 'yajuego.co',
    'interwetten.com', 'bet-at-home.com', 'betvictor.com', 'coral.co.uk', 'skybet.com',
    'virginbet.com', 'betfred.com', 'ggpoker.com', 'partypoker.com', 'winamax.fr',
    'pmu.fr', 'parionssport.fdj.fr', 'admiralbet.com', 'merkur.de', 'americascardroom.eu',
    'smarkets.com', 'matchbook.com', 'thelotter.com', 'lottoland.com', 'jackpotjoy.com',
    'lottomart.com', 'codere.com',
  ],
  adult: [
    'pornhub.com', 'xvideos.com', 'xnxx.com', 'xhamster.com', 'redtube.com',
    'youporn.com', 'onlyfans.com', 'chaturbate.com', 'brazzers.com', 'spankbang.com',
    'eporner.com', 'tnaflix.com', 'youjizz.com', 'porn.com', 'fapello.com',
    'motherless.com', 'rule34.xxx', 'nhentai.net', 'hanime.tv', 'stripchat.com',
    'bongacams.com', 'cam4.com', 'xhamsterlive.com', 'tube8.com', 'txxx.com',
    'hclips.com', 'upornia.com', 'hqporner.com', 'porntrex.com', 'porn300.com',
    'sex.com', 'xxx.com', 'beeg.com', 'drtuber.com', 'nuvid.com',
    'sunporno.com', '4tube.com', 'porndig.com', 'pornone.com', 'fapvid.com',
    'porngo.com', 'thumbzilla.com', 'keezmovies.com', 'extremetube.com', '3movs.com',
    'gotporn.com', 'sexvid.xxx', 'porn555.com', 'fuq.com', 'pornhd.com',
    'analdin.com', 'vjav.com', 'spankwire.com', 'empflix.com', 'slutload.com',
    'ixxx.com', 'elephanttube.com', 'camwhores.tv', 'javhd.com', 'jav.guru',
    'javmost.com', 'javdoe.com', 'missav.com', 'hentaihaven.xxx', 'hentai2read.com',
    'hentaifox.com', 'e-hentai.org', 'hentaicity.com', 'luscious.net', 'multporn.net',
    'rule34video.com', 'gelbooru.com', 'e621.net', 'sankakucomplex.com', 'pornpics.com',
    'imagefap.com', 'fapality.com', 'livejasmin.com', 'camsoda.com', 'myfreecams.com',
    'jerkmate.com', 'flirt4free.com', 'imlive.com', 'streamate.com', 'xlovecam.com',
    'fansly.com', 'manyvids.com', 'clips4sale.com', 'coomer.su', 'kemono.su',
    'realitykings.com', 'naughtyamerica.com', 'bangbros.com', 'mofos.com', 'digitalplayground.com',
    'adulttime.com', 'blacked.com', 'tushy.com', 'vixen.com', 'deeper.com',
    'wicked.com', 'evilangel.com', 'metart.com', 'twistys.com', 'nubiles.net',
    'teamskeet.com', 'fakehub.com', 'adultfriendfinder.com', 'ashleymadison.com', 'fetlife.com',
    'literotica.com', 'theporndude.com', 'javbus.com', 'javlibrary.com', 'supjav.com',
    'jable.tv', 'njav.tv', 'hitomi.la', 'hentaigasm.com', 'hentaistream.com',
    'simply-hentai.com', 'hentai.tv', 'xbooru.com', 'tbib.org', 'yande.re',
    'konachan.com', 'donmai.us', 'paheal.net', 'erome.com', 'avgle.com',
    '91porn.com', 'vporn.com', 'perfectgirls.net', 'pornhat.com', 'hdzog.com',
    'winporn.com', 'fancentro.com', 'iwantclips.com', 'fanvue.com', 'loyalfans.com',
    'justfor.fans', 'cherry.tv', 'camster.com', 'cams.com', 'royalcams.com',
    'scrolller.com',
  ],
  piracy: [
    'thepiratebay.org', '1337x.to', '1337x.st', 'yts.mx', 'yts.bz',
    'yts.am', 'yts.rs', 'torrentgalaxy.to', 'torrentgalaxy.mx', 'nyaa.si',
    'nyaa.land', 'limetorrents.lol', 'limetorrents.cc', 'torlock.com', 'eztv.re',
    'eztvx.to', 'magnetdl.com', 'glodls.to', 'torrentdownloads.pro', 'torrentfunk.com',
    'bitsearch.to', 'ext.to', 'rutracker.org', 'kickasstorrents.to', 'katcr.co',
    'rargb.to', 'rarbgmirror.org', 'skidrowreloaded.com', 'fitgirl-repacks.site', 'zooqle.com',
    'yourbittorrent.com', 'demonoid.is', 'tamilrockers.ws', 'tamilmv.cc', 'fmovies.to',
    'fmovies.co', 'fmoviesz.to', 'fmovies24.to', 'bflix.to', 'bflixhd.to',
    'sflix.to', 'sflix.ps', 'sflixhd.to', '123movies.net', '123moviesfree.net',
    'gomovies.sx', 'gomovies.gg', 'gostream.to', 'solarmovie.pe', 'solarmovies.to',
    'soap2day.day', 'soap2day.to', 'soap2dayx.to', 'putlocker.pe', 'primewire.mov',
    'primewire.li', 'watchseries.mx', 'watchserieshd.to', 'hdtoday.tv', 'hdtoday.cc',
    'flixhq.to', 'flixhq.click', 'losmovies.id', 'hurawatch.to', 'hurawatch.cc',
    'lookmovie.io', 'lookmovie2.to', 'flixtor.to', 'flixtor.se', 'yesmovies.ag',
    'yesmovies.mn', 'movies123.net', '0123movie.net', 'cuevana3.io', 'pelisplus.to',
    'hianime.to', 'hianime.nz', 'aniwave.to', 'aniwave.se', '9anime.to',
    '9animetv.to', 'gogoanime.by', 'gogoanime.tel', 'gogoanimes.fi', 'animekai.to',
    'animesuge.to', 'animeflix.to', 'animepahe.ru', 'zoro.to', 'zorox.to',
    'aniwatch.to', 'kissanime.com.ru', 'animixplay.to', 'streameast.is', 'streameast.live',
    'streameast.to', 'streameast.app', 'crackstreams.me', 'crackstreams.biz', 'crackstreams.io',
    'methstreams.com', 'buffstreams.app', 'buffstreams.sx', 'sportsurge.net', 'sportsurge.club',
    'vipbox.lc', 'vipleague.im', 'totalsportek.com', 'streamed.su', 'soccerstreams.net',
    'nbastreams.to', 'mangakakalot.com', 'manganato.com', 'chapmanganato.to', 'manganelo.com',
    'manganelo.tv', 'mangakakalot.tv', 'mangafire.to', 'mangapark.net', 'mangabuddy.com',
    'mangareader.to', 'vegamovies.to', 'hdhub4u.tv', 'movierulz.vc', 'filmywap.com',
    'bolly4u.org', 'rutracker.net', 'rutor.org', 'rutor.info', 'rutor.is',
    'nnmclub.to', 'nnm-club.me', 'kinozal.tv', 'kinozal.me', 'filmix.ac',
    'hdrezka.ag', 'hdrezka.me', 'zamunda.net', 'zamunda.se', 'maxitorrent.net',
    'yggtorrent.top', 'yggtorrent.wtf', 'ygg.re', 'cpasbien.cl', 'torrent9.pe',
    'torrent9.fm', 'oxtorrent.cc', 'oxtorrent.com', 'wawacity.lol', 'wawacity.boats',
    'zone-telechargement.boats', 'zone-annuaire.com', 'tirexo.cx', 'darkino.io', 'zetorrents.com',
    'divxtotal.wtf', 'divxtotal.mov', 'divxatope.net', 'dontorrent.org', 'todotorrents.org',
    'pediatorrent.com', 'elitetorrent.wtf', 'mejortorrent.eu', 'devil-torrents.pl', 'ex-torrenty.org',
    'electro-torrent.pl', 'polskie-torrenty.eu', 'helltorrents.com', 'cuevana3.is', 'cuevana3.pro',
    'cuevanahd.mov', 'pelisplus.so', 'pelisplushd.net', 'pelisplushd.to', 'repelis24.org',
    'repelishd.la', 'gnula.nu', 'gnulahd.nu', 'pelisflix.li', 'cinecalidad.fm',
    'cinecalidad.tw', 'hdfull.cat', 'megaflix.tv', 'megaflix.online', 'redecanais.gs',
    'redecanais.al', 'redecanais.fm', 'vizer.tv', 'vizertv.in', 'pobreflix.icu',
    'pobreflixtv.app', 'overflix.tv', 'ultraflix.online', 'novaflix.tv', 'topflixhd.live',
    'assistirseriesonline.cc', 'wiflix.cool', 'flemmix.com', 'french-stream.li', 'frenchstream.icu',
    'papystreaming.cool', 'streamonsport.click', 'dpstream.io', 'filmoflix.cc', 'voirfilms.al',
    'voirseries.io', 'kinox.to', 'kinox.party', 'movie4k.to', 'movie4k.sx',
    'serienstream.to', 's.to', 'bs.to', 'aniworld.to', 'megakino.co',
    'streamkiste.tv', 'kinoger.re', 'cine.to', 'altadefinizione.tienda', 'altadefinizione01.space',
    'streamingcommunity.computer', 'streamingcommunity.prof', 'tantifilm.nl', 'cb01.tienda', 'cineblog01.solar',
    'guardaserie.media', 'ilgeniodellostreaming.cx', 'casacinema.media', 'egybest.network', 'egy.best',
    'cima4u.cam', 'cimaclub.cyou', 'akwam.to', 'akoam.net', 'faselhd.care',
    'faselhds.center', 'shahid4u.cam', 'mycima.cyou', 'movizland.cyou', 'arabseed.ink',
    'fushaar.com', 'hdhub4u.fail', 'vegamovies.nl', 'vegamovies.tv', 'filmywap.com.se',
    'movierulz.cash', '5movierulz.cash', '9xmovies.press', 'mkvcinemas.mkv', 'filmyzilla.com.se',
    'filmyzilla4u.com', 'bollyflix.fyi', 'sdmoviespoint.cool', 'khatrimaza.cx', 'pagalmovies.tv',
    'mp4moviez.skin', 'extramovies.cx', 'gogoanime.org.vc', 'anitaku.bz', 'anitaku.pe',
    'animedao.to', 'animeflv.net', 'kayoanime.com', 'kissmanga.in', 'mangakakalot.gg',
    'manganato.gg', 'daddylive.sx', 'daddylive.me', 'daddylivehd.sx', 'crackstreams.net',
    'footybite.to', 'totalsportek.to', 'viprow.nu', 'viprow.me', '720pstream.nu',
    'nbastreams.gg', 'livetv.sx', 'ssports.click', 'pirlotv.fm', 'fitgirl-repacks.org',
    'skidrowcodex.net', 'igg-games.com', 'oceanofgames.com', 'getintopc.com', 'filecr.com',
    'rlsbb.ru', 'nsane.down', 'gload.to', 'steamunlocked.net', 'ovagames.com',
    'gamingbeasts.com', 'worldofpcgames.com', 'crackingpatching.com', 'freeprosoftz.com', 'romsmania.cc',
    'romsfun.com', 'romspedia.com', 'emuroms.org', 'coolrom.com.au', 'edgeemu.net',
    'libgen.is', 'libgen.li', 'libgen.st', 'libgen.rs', 'libgen.gs',
    'libgen.rocks', 'library.lol', 'annas-archive.org', 'annas-archive.se', 'annas-archive.li',
    'z-lib.org', 'z-lib.io', 'z-library.sk', 'zlibrary-global.se', '1lib.sk',
    'oceanofpdf.com', 'audiobookbay.is', 'audiobookbay.lu', 'sci-hub.se', 'sci-hub.st',
    'sci-hub.ru', 'pdfdrive.com', 'ebook-hunter.org',
  ],
  threat: [
    'youtubedownloadernew.com', 'lishbos.com', 'epicsofts.com', 'antivirustechies.us',
  ],
};

const norm = (d: string) =>
  d.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '').replace(/^www\./, '');

// Compute the effective domain list from a blocker config: enabled categories +
// personal blocks, minus the allow list.
export function effectiveDomains(cfg: BlockerConfig): string[] {
  const set = new Set<string>();
  (Object.keys(CATEGORY_DOMAINS) as BlockerCategory[]).forEach((k) => {
    if (cfg.categories?.[k]) CATEGORY_DOMAINS[k].forEach((d) => set.add(norm(d)));
  });
  (cfg.personalBlock || []).forEach((d) => { const n = norm(d); if (n.includes('.')) set.add(n); });
  (cfg.personalAllow || []).forEach((d) => set.delete(norm(d)));
  set.delete('');
  return [...set];
}
